---
name: ai_tool_info
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/128501
rollout_issue_url:
milestone: '16.3'
type: development
group: group::ai framework
default_enabled: false
