---
name: ci_support_include_rules_changes
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/129866
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/421608
milestone: '16.4'
type: development
group: group::pipeline authoring
default_enabled: false
