---
name: errors_utf_8_encoding
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/129217
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/422061
milestone: '16.4'
type: development
group: group::source code
default_enabled: true
