---
name: explain_current_blob
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/128342/
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/420959
milestone: '16.3'
type: development
group: group::ai framework
default_enabled: false
