---
name: maintainers_allowed_to_read_group_runners
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/128607
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/421550
milestone: '16.4'
type: development
group: group::runner
default_enabled: false
